#ifndef __CHARSET_H
#define __CHARSET_H

#define CHARSET_NUMERIC "0123456789"
#define CHARSET_NUMERIC_LEN (sizeof(CHARSET_NUMERIC) - 1)

#define CHARSET_ALPHA "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define CHARSET_ALPHA_LEN (sizeof(CHARSET_ALPHA) - 1)

#define CHARSET_ALPHA_NUMERIC "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#define CHARSET_ALPHA_NUMERIC_LEN (sizeof(CHARSET_ALPHA_NUMERIC) - 1)

#define CHARSET_LOWERALPHA "abcdefghijklmnopqrstuvwxyz"
#define CHARSET_LOWERALPHA_LEN (sizeof(CHARSET_LOWERALPHA) - 1)

#define CHARSET_LOWERALPHA_NUMERIC "abcdefghijklmnopqrstuvwxyz0123456789"
#define CHARSET_LOWERALPHA_NUMERIC_LEN (sizeof(CHARSET_LOWERALPHA_NUMERIC) - 1)

#define CHARSET_MIXALPHA "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define CHARSET_MIXALPHA_LEN (sizeof(CHARSET_MIXALPHA) - 1)

#define CHARSET_MIXALPHA_NUMERIC "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#define CHARSET_MIXALPHA_NUMERIC_LEN (sizeof(CHARSET_MIXALPHA_NUMERIC) - 1)

#define CHARSET_ASCII_32_95 " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
#define CHARSET_ASCII_32_95_LEN (sizeof(CHARSET_ASCII_32_95) - 1)

#define CHARSET_ASCII_32_65_123_4 " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`{|}~"
#define CHARSET_ASCII_32_65_123_4_LEN (sizeof(CHARSET_ASCII_32_65_123_4) - 1)

#define CHARSET_ALPHA_NUMERIC_SYMBOL32_SPACE "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_+=~`[]{}|\\:;\"'<>,.?/ "
#define CHARSET_ALPHA_NUMERIC_SYMBOL32_SPACE_LEN (sizeof(CHARSET_ALPHA_NUMERIC_SYMBOL32_SPACE) - 1)


char *validate_charset(char *charset_name);
void get_valid_charsets(char *buf, unsigned int buf_size);

#endif
